In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv("..//Data/Final_data.csv")
print(data)

        Unnamed: 0  Operator Network Type In Out Travelling  \
0                0      Idea           3G            Indoor
1                1      Idea           4G           Outdoor
2                2      Idea           4G            Indoor
3                3      RJio           4G           Outdoor
4                4      RJio           4G           Outdoor
...            ...       ...          ...               ...
196625      196971      RJio           4G           Outdoor
196626      196972  Vodafone           4G           Outdoor
196627      196973      RJio           4G            Indoor
196628      196974      BSNL           2G        Travelling
196629      196975  Vodafone           3G            Indoor

        Call Drop Category   State Name  Latitude  Longitude
0       Poor Voice Quality  Maharashtra        19         72
1       Poor Voice Quality  Maharashtra        19         72
2             Satisfactory  Maharashtra        19         72
3             Satisfactory  Uttarakhand        30         78
4             Satisfactory  Uttarakhand        30         78
...                    ...          ...       ...        ...
196625        Satisfactory  Maharashtra        18         73
196626  Poor Voice Quality      Gujarat        23         72
196627        Call Dropped       Odisha        20         85
196628        Call Dropped  Maharashtra        17         74
196629        Satisfactory  Maharashtra        19         72

[196630 rows x 8 columns]

In [3]:
df = pd.DataFrame(data)

In [4]:
df

,Unnamed: 0,Operator,Network Type,In Out Travelling,Call Drop Category,State Name,Latitude,Longitude
0,0,Idea,3G,Indoor,Poor Voice Quality,Maharashtra,19,72
1,1,Idea,4G,Outdoor,Poor Voice Quality,Maharashtra,19,72
2,2,Idea,4G,Indoor,Satisfactory,Maharashtra,19,72
3,3,RJio,4G,Outdoor,Satisfactory,Uttarakhand,30,78
4,4,RJio,4G,Outdoor,Satisfactory,Uttarakhand,30,78
...,...,...,...,...,...,...,...,...
196625,196971,RJio,4G,Outdoor,Satisfactory,Maharashtra,18,73
196626,196972,Vodafone,4G,Outdoor,Poor Voice Quality,Gujarat,23,72
196627,196973,RJio,4G,Indoor,Call Dropped,Odisha,20,85
196628,196974,BSNL,2G,Travelling,Call Dropped,Maharashtra,17,74
196629,196975,Vodafone,3G,Indoor,Satisfactory,Maharashtra,19,72

In [ ]:


from mpl_toolkits.basemap import Basemap
import matplotlib.pyplot as plt
%matplotlib inline

In [9]:
print(df.Latitude.mean())
print(df.Longitude.mean())

20.585317601586738
77.64823780704877

These coordinates belong to Maharashtra. Maharashtra has the largest data representation,

In [10]:

df_Airtel = df[df.Operator == 'Airtel']
df_BSNL = df[df.Operator == 'BSNL']
df_Idea = df[df.Operator == 'Idea']
df_RJio = df[df.Operator == 'RJio']
df_Vodafone = df[df.Operator == 'Vodafone']
df_Others = df[df.Operator == 'Others']

In [11]:

lon_airtel, lat_airtel = list(df_Airtel[df_Airtel.Longitude != -1.000000].Longitude), list(df_Airtel[df_Airtel.Latitude != -1.000000].Latitude)
lon_bsnl, lat_bsnl = list(df_BSNL[df_BSNL.Longitude != -1.000000].Longitude), list(df_BSNL[df_BSNL.Latitude != -1.000000].Latitude)
lon_idea, lat_idea = list(df_Idea[df_Idea.Longitude != -1.000000].Longitude), list(df_Idea[df_Idea.Latitude != -1.000000].Latitude)
lon_rjio, lat_rjio = list(df_RJio[df_RJio.Longitude != -1.000000].Longitude), list(df_RJio[df_RJio.Latitude != -1.000000].Latitude)
lon_voda, lat_voda = list(df_Vodafone[df_Vodafone.Longitude != -1.000000].Longitude), list(df_Vodafone[df_Vodafone.Latitude != -1.000000].Latitude)
lon_others, lat_others = list(df_Others[df_Others.Longitude != -1.000000].Longitude), list(df_Others[df_Others.Latitude != -1.000000].Latitude)

In [ ]:
plt.figure(figsize=(20,12))
# fig.set_size_inches(8, 6.5)

map1 = Basemap(projection='merc',
            llcrnrlat=0, urcrnrlat=38,
            llcrnrlon=60, urcrnrlon=100,
            lat_ts=0,
            resolution='c')

map1.bluemarble(scale=0.2)   # full scale will be overkill
map1.drawcoastlines(color='white', linewidth=0.2)  # add coastlines

x_Airtel, y_Airtel = map1(lon_airtel, lat_airtel)
plt.scatter(x_Airtel, y_Airtel, 10, marker='o', color='#1f77b4', label = 'Airtel')

x_BSNL, y_BSNL = map1(lon_bsnl, lat_bsnl)
plt.scatter(x_BSNL, y_BSNL, 10, marker='o', color='#ff7f0e', label = 'BSNL')

x_Idea, y_Idea = map1(lon_idea, lat_idea)
plt.scatter(x_Idea, y_Idea, 10, marker='o', color='#2ca02c', label = 'Idea')

x_RJio, y_RJio = map1(lon_rjio, lat_rjio) 
plt.scatter(x_RJio, y_RJio, 10, marker='o', color='#d62728', label = 'RJio')

x_Vodafone, y_Vodafone = map1(lon_voda, lat_voda)
plt.scatter(x_Vodafone, y_Vodafone, 10, marker='o', color='#9467bd', label = 'Vodafone')

x_Others, y_Others = map1(lon_others, lat_others)
plt.scatter(x_Others, y_Others, 10, marker='o', color='#8c564b', label = 'Others')        

plt.legend()
plt.savefig('result.png')